### ISSUE TITLE
Set venue on all markdown drafts

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http-extensions#1792]
Here's what I've used:

```yaml
venue:
  group: httpbis
  type: Working
  mail: ietf-http-wg@w3.org
  arch: https://lists.w3.org/Archives/Public/ietf-http-wg/
  github: httpwg/http-extensions
```
