### ISSUE TITLE
Digest: update references for SHA algorithms.

### ISSUE THREAD

**Issue by ioggstream** [httpwg/http-extensions#832]
## Question

Should we update the FIPS180 reference to the latest one?

## Context

NIST updated the document defining SHA-* algoritms.

The latest reference is

```
  FIPS180-4:
    title: NIST FIPS 180-4, Secure Hash Standard
    author:
      name: NIST
      ins: National Institute of Standards and Technology, U.S. Department of Commerce
    date: 2015-08
    target: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf
```

digest-headers references preserve the ones cited in RFC3230 and subsequent.
