### ISSUE TITLE
Digest headers example 7.1.4 is wrong

### ISSUE THREAD

**Issue by LPardue** [httpwg/http-extensions#881]
I think the digest for the response is incorrect because the encoding is br but the digest is the same as other examples with identity encoding.

```
Response:

  Content-Type: application/json
  Content-Encoding: br
  Digest: sha-256=X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=

  iwiAeyJoZWxsbyI6ICJ3b3JsZCJ9Aw==
```
